# -*- coding: utf-8 -*-
"""Main_plot.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1F0A6OXgXSlc1FggABwqMf8h-Qj5aahAx
"""

import scipy.io as io
import os
import torch
import numpy as np
from torch.utils.data import DataLoader, Dataset
import torchvision.transforms
import torch.nn as nn
from torch.autograd import Variable
import matplotlib.pyplot as plt
from torch_radon import Radon, RadonFanbeam
from kornia import rotate
from random import choice
from network_arch import UNet
from data import dataloader_train,dataloader_test
from utils import PSNR_cal,show_images
from train import EI_train,Supervised_train
from test import EI_test,Supervised_test

epochs=5000
batch_size=2
learning_rate=0.0005
weight_dec=1e-8
alpha=100
image_size=128
det_count = int(np.sqrt(2)*image_size + 0.5)
loss_fn = nn.MSELoss().cuda()
Supervised_model = UNet().cuda()
EI_model = UNet().cuda()
optimizer_Sup = torch.optim.Adam(Supervised_model.parameters(), lr=learning_rate, weight_decay=weight_dec)
optimizer_EI = torch.optim.Adam(EI_model.parameters(), lr=learning_rate, weight_decay=weight_dec)
scheduler_Sup = torch.optim.lr_scheduler.MultiStepLR(optimizer_Sup, milestones=[2000,3000,4000], gamma=0.2)
scheduler_EI = torch.optim.lr_scheduler.MultiStepLR(optimizer_EI, milestones=[2000,3000,4000], gamma=0.2)
Sup_psnrs_train,Sup_psnrs_test= [],[]
EI_psnrs_train,EI_psnrs_test= [],[]
gt_path = ('/content/drive/MyDrive/Final_year_project/src/Dataset/Groud_Truth_train.mat')
gt_path_test = ('/content/drive/MyDrive/Final_year_project/src/Dataset/Groud_Truth_test.mat')

dataloader_train,dataset_train=dataloader_train(gt_path,batch_size)
dataloader_test,dataset_test=dataloader_test(gt_path_test,batch_size)

EI_Model_path1 = '/content/drive/MyDrive/Final_year_project/Trained_model/Transformation_model/30-views/1-trans'
EI_Model_path2 = '/content/drive/MyDrive/Final_year_project/Trained_model/Transformation_model/30-views/3-trans'
EI_Model_path3 = '/content/drive/MyDrive/Final_year_project/Trained_model/Transformation_model/30-views/5-trans'
EI_Model_path4 = '/content/drive/MyDrive/Final_year_project/Trained_model/Transformation_model/30-views/7-trans'
EI_Model_path5 = '/content/drive/MyDrive/Final_year_project/Trained_model/Transformation_model/30-views/10-trans'
EI_Model = [EI_Model_path1,EI_Model_path2,EI_Model_path3,EI_Model_path4,EI_Model_path5]
EI_psnr = []
s = slice(40,49,1)
trans = [1,3,5,7,10]
n_views=30
angles = np.linspace(0, np.pi, n_views, endpoint=False)
radon = Radon(image_size, angles, clip_to_circle=False, det_count=det_count)
for i in range(0,5):
  EI_path = EI_Model[i]
  EI_psnrs_train,EI_psnrs_test = EI_test(dataloader_test, EI_path, loss_fn,radon,epochs)
  EI_psnrs_test=EI_psnrs_test[s]
  EI_psnr.append(np.mean(EI_psnrs_test))

plt.figure(figsize=(10,4))
plt.plot(trans,EI_psnr,label="EI_psnrs")
plt.xlabel('trans')
# Set the y axis label of the current axis.
plt.ylabel('PSNR(dB)')
# Set a title of the current axes.
#plt.title('Two or more lines on same plot with suitable legends ')
# show a legend on the plot
plt.legend()
# Display a figure.
plt.savefig('/content/drive/MyDrive/Final_year_project/Figures/PSNR-trans.png')
plt.show()

# epochs=5000
# batch_size=2
# learning_rate=0.0005
# weight_dec=1e-8
# alpha=100
# image_size=128
# det_count = int(np.sqrt(2)*image_size + 0.5)
# loss_fn = nn.MSELoss().cuda()
# Supervised_model = UNet().cuda()
# EI_model = UNet().cuda()
# optimizer_Sup = torch.optim.Adam(Supervised_model.parameters(), lr=learning_rate, weight_decay=weight_dec)
# optimizer_EI = torch.optim.Adam(EI_model.parameters(), lr=learning_rate, weight_decay=weight_dec)
# scheduler_Sup = torch.optim.lr_scheduler.MultiStepLR(optimizer_Sup, milestones=[2000,3000,4000], gamma=0.2)
# scheduler_EI = torch.optim.lr_scheduler.MultiStepLR(optimizer_EI, milestones=[2000,3000,4000], gamma=0.2)
# Sup_psnrs_train,Sup_psnrs_test= [],[]
# EI_psnrs_train,EI_psnrs_test= [],[]
# gt_path = ('/content/drive/MyDrive/Final_year_project/src/Dataset/Groud_Truth_train.mat')
# gt_path_test = ('/content/drive/MyDrive/Final_year_project/src/Dataset/Groud_Truth_test.mat')

# dataloader_train,dataset_train=dataloader_train(gt_path,batch_size)
# dataloader_test,dataset_test=dataloader_test(gt_path_test,batch_size)

# EI_Model_path = '/content/drive/MyDrive/Final_year_project/Trained_model/EI_model'
# Supervised_Model_path = '/content/drive/MyDrive/Final_year_project/Trained_model/Supervised_model'

# EI_psnr,Sup_psnr,FBP_psnr,views=[],[],[],[]
# s = slice(40,49,1)
# for i in np.linspace(10,100,10, endpoint=True):
#   EI_path = os.path.join(EI_Model_path, '{}-views'.format(int(i)))
#   Supervised_path = os.path.join(Supervised_Model_path, '{}-views'.format(int(i)))
#   n_views=int(i)
#   angles = np.linspace(0, np.pi, n_views, endpoint=False)
#   radon = Radon(image_size, angles, clip_to_circle=False, det_count=det_count)
#   Sup_psnrs_train,Sup_psnrs_test = Supervised_test(dataloader_test, Supervised_path, loss_fn,epochs,radon)
#   EI_psnrs_train,EI_psnrs_test = EI_test(dataloader_test, EI_path, loss_fn,radon,epochs)
#   Sup_psnrs_test=Sup_psnrs_test[s]
#   EI_psnrs_test=EI_psnrs_test[s]
#   FBP_list = []
#   for j in range(0,10):
#     image = torch.FloatTensor(dataset_test[j].float()).cuda()
#     sinogram = radon.forward(image)
#     filtered_sinogram = radon.filter_sinogram(sinogram)
#     fbp = radon.backprojection(filtered_sinogram)
#     FBP_list.append(PSNR_cal(image,fbp,torch.max(fbp)))
#   FBP_psnr.append(np.mean(FBP_list))
#   EI_psnr.append(np.mean(EI_psnrs_test))
#   Sup_psnr.append(np.mean(Sup_psnrs_test))
#   views.append(int(i))

# plt.figure(figsize=(10,4))
# plt.plot(views,Sup_psnr,label="Sup_psnrs")
# plt.plot(views,EI_psnr,label="EI_psnrs")
# plt.plot(views,FBP_psnr,label="FBP_psnrs")
# plt.xlabel('Views')
# # Set the y axis label of the current axis.
# plt.ylabel('PSNR(dB)')
# # Set a title of the current axes.
# #plt.title('Two or more lines on same plot with suitable legends ')
# # show a legend on the plot
# plt.legend()
# # Display a figure.
# plt.savefig('/content/drive/MyDrive/Final_year_project/Figures/PSNR-views.png')
# plt.show()